// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccferYD92QVBZTI5y3SoxVEkmxbZkEuE',
    appId: '1:646771593611:web:dbe8f60d5fe83b273e9f8e',
    messagingSenderId: '646771593611',
    projectId: 'flutter-da13f',
    authDomain: 'flutter-da13f.firebaseapp.com',
    storageBucket: 'flutter-da13f.appspot.com',
    measurementId: 'G-K7ZMN21W5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFBepApPbe_bLUZQ1VfM0Whf0O171nw-w',
    appId: '1:646771593611:android:0373a2abbdba67543e9f8e',
    messagingSenderId: '646771593611',
    projectId: 'flutter-da13f',
    storageBucket: 'flutter-da13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79WXjTGNKXge29k6L7TPuMCOAtbQJJIo',
    appId: '1:646771593611:ios:b3310299a40322ce3e9f8e',
    messagingSenderId: '646771593611',
    projectId: 'flutter-da13f',
    storageBucket: 'flutter-da13f.appspot.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB79WXjTGNKXge29k6L7TPuMCOAtbQJJIo',
    appId: '1:646771593611:ios:b1a600b91f28d3553e9f8e',
    messagingSenderId: '646771593611',
    projectId: 'flutter-da13f',
    storageBucket: 'flutter-da13f.appspot.com',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );
}
